# Generated by Django 4.2.1 on 2023-05-19 15:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaDeServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 5, 19, 12, 18, 37, 78575))),
                ('fecha_reserva', models.DateTimeField(default=datetime.datetime(2023, 5, 19, 12, 18, 37, 78576))),
                ('precio', models.PositiveBigIntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cliente')),
            ],
        ),
    ]
