# Generated by Django 4.2 on 2023-05-22 11:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reservadeservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('numero_documento', models.IntegerField()),
                ('fecha_alta', models.DateTimeField(default=datetime.datetime(2023, 5, 22, 8, 9, 44, 878581))),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['activo', 'apellido', 'numero_documento'],
            },
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 5, 22, 8, 9, 44, 878580))),
                ('fecha_reserva', models.DateTimeField(default=datetime.datetime(2023, 5, 22, 8, 9, 44, 878581))),
                ('precio', models.PositiveBigIntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cliente')),
            ],
            options={
                'ordering': ['fecha_creacion', 'cliente', 'precio'],
            },
        ),
        migrations.DeleteModel(
            name='ReservaDeServicio',
        ),
    ]
