# Generated by Django 4.2.1 on 2023-05-24 20:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_auto_20230522_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['activo', 'apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('numero_documento', models.IntegerField()),
                ('fecha_alta', models.DateTimeField(default=datetime.datetime(2023, 5, 24, 17, 30, 23, 363421))),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['activo', 'apellido', 'numero_documento'],
            },
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 5, 24, 17, 30, 23, 362420))),
                ('fecha_reserva', models.DateTimeField(default=datetime.datetime(2023, 5, 24, 17, 30, 23, 362421))),
                ('precio', models.PositiveBigIntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cliente')),
            ],
            options={
                'ordering': ['fecha_creacion', 'cliente', 'precio'],
            },
        ),
    ]
