# Generated by Django 4.2.1 on 2023-05-24 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_cliente_coordinador_alter_empleado_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinador',
            name='fecha_alta',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 17, 31, 28, 579132)),
        ),
        migrations.AlterField(
            model_name='reservaservicio',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 17, 31, 28, 577132)),
        ),
        migrations.AlterField(
            model_name='reservaservicio',
            name='fecha_reserva',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 17, 31, 28, 577132)),
        ),
    ]
