# Generated by Django 4.2.1 on 2023-05-24 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_coordinador_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre', 'precio', 'activo']},
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='fecha_alta',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='numero_documento',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservaservicio',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reservaservicio',
            name='fecha_reserva',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='reservaservicio',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
