# Generated by Django 4.2.1 on 2023-05-27 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_servicio_options_alter_coordinador_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinador',
            options={'ordering': ['apellido', 'activo', 'numero_documento']},
        ),
    ]
