# Generated by Django 4.2.1 on 2023-06-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_coordinador_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['apellido', 'activo', 'nombre']},
        ),
    ]
